BcbDatabase/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('ComicDatabase.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('ComicDatabase.api.urls')),
]

ComicDatabase/api/urls.py
from django.conf.urls import url, include

from ComicDatabase.api import api

app_name = "Api"

urlpatterns = [
    url(r'^$', api.index, name='index'),
    url(r'^v1.0/', include('ComicDatabase.api.v1_0.urls'))
]

ComicDatabase/api/v1_0/urls.py
from django.conf.urls import url

from ComicDatabase.api.v1_0 import api

urlpatterns = [
    url(r'^characters/', api.get_characters),
    url(r'^chapters/', api.get_chapters),
    url(r'^lines/(?P<chapter_number>[0-9.]*)/(?P<page_number>[0-9]+)/new/(?P<character_id>[0-9]+?)/(?P<line_text>.*)/', api.add_line),
    url(r'^lines/(?P<chapter_number>[0-9.]*)/(?P<page_number>[0-9]+)/', api.get_lines),
    url(r'^lines/delete/(?P<id>[0-9]*)/', api.delete_line),
    url(r'^lines/order/(?P<id>[0-9]*)/(?P<difference>[0-9-]*)/', api.change_line_order),
]

ComicDatabase/urls.py
from django.conf.urls import url, include

from ComicDatabase import auth_views
from ComicDatabase import views

app_name = "ComicDatabase"
urlpatterns = [
    url(r'^api/', include('ComicDatabase.api.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^c(?P<chapternr>[0-9\.]+)/p(?P<page>[0-9\.]+)/(?P<terms>.*)?/?$', views.page, name='page'),
    url(r'^c(?P<chapter_number>[0-9\.]+)/?', views.chapter, name='chapter'),
    url(r'^a/c(?P<chapternr>[0-9\.]+)/p(?P<page>[0-9\.]+)/(?P<terms>.*)?/?$', views.page_edit, name='page_edit'),
    url(r'^search/(?P<terms>.*)?/?$', views.search, name='search'),
    url(r'^accounts/login/.*', auth_views.login_page, name='login'),
    url(r'^accounts/logout/.*', auth_views.logout_page, name='logout'),
]

ComicDatabase/models.py
from django.db import models


class Chapter(models.Model):
    """A single chapter"""

    number = models.DecimalField(decimal_places=1, max_digits=4)
    """The chapter number"""

    title = models.TextField(max_length=200)
    """The chapter title"""

    description = models.TextField(max_length=200)
    """The chapter description"""

    pageCount = models.IntegerField()
    """The amount of pages that are in this chapter"""

    extension = models.TextField(default=".png")
    """The extension of the pages in this chapter"""

    class Meta:
        ordering = ['number']

    def __str__(self):
        """'Chapter 1: Simple Pleasures (6 pages)'"""
        return "Chapter %s: %s (%s pages)" % (self.number, self.title, self.pageCount)


class Species(models.Model):
    """A single species (think cat, dog)"""

    name = models.TextField(max_length=200)
    """The name of the species"""

    def __str__(self):
        """'cat'"""
        return self.name


class Character(models.Model):
    """A character in the comic"""

    name = models.TextField(max_length=200)
    """The name of the character"""

    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    """The species of the character"""

    def __str__(self):
        """'Lucy (cat)'"""
        return "%s (%s)" % (self.name, self.species)


class Line(models.Model):
    """A line, said by a character on a page"""

    class Meta:
        unique_together = (('chapter', 'page', 'order'),)
        ordering = ['chapter', 'page', 'order']

    text = models.TextField(max_length=500)
    """The text of the line"""

    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    """The character saying the line"""

    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    """The chapter this line is in"""

    page = models.IntegerField()
    """The page this line is on"""

    order = models.IntegerField(default=0)
    """An ordering integer so that the lines can be re-ordered"""

    def __str__(self):
        """'[1:1] <Radio> Welcome to a lovely sunny Saturday, America! [...]'"""
        return "[%s/%s:%s] <%s> %s" % (self.chapter.number, self.page, self.order, self.character, self.text)

ComicDatabase/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse

from ComicDatabase.classes import SearchForm
from ComicDatabase.models import Line, Chapter, Character


def nav(request, chapter_=None, page_=None, terms=None, editing=False):
    """Render the navigation view"""

    all_chapters = Chapter.objects.all()

    return render_to_string('ComicDatabase/nav.html',
                            {'chapter': chapter_, 'page': page_, 'terms': terms, 'user': request.user, 'editing': editing, 'all_chapters': all_chapters}, request)


def index(request):
    return render(request, 'ComicDatabase/index_list.html', {
        'nav': nav(request), 'chapters': Chapter.objects.all()
    })


# Create your views here.
def page(request, chapternr, page, terms):
    current_chapter = Chapter.objects.filter(number=chapternr).first()  # type: Chapter

    lines = Line.objects.filter(chapter__number=current_chapter.number, page=page).order_by('order')

    nav_box = nav(request, current_chapter, page, terms)

    if float(current_chapter.number) == int(float(current_chapter.number)):
        current_chapter.number = int(float(current_chapter.number))

    page = int(page)

    new_chapter = None

    if page < 1:
        new_chapter = Chapter.objects.filter(number__lt=chapternr).first()
        if new_chapter is None:
            new_chapter = current_chapter
        page = new_chapter.pageCount
    if page > current_chapter.pageCount:
        new_chapter = Chapter.objects.filter(number__gt=chapternr).order_by('number').first()
        if new_chapter is None:
            new_chapter = current_chapter
        page = 1

    if new_chapter is not None:
        current_chapter = new_chapter

    return render(request, 'ComicDatabase/page.html',
                  {'chapter': current_chapter, 'page': page, 'terms': terms, 'lines': lines, 'nav': nav_box})


@login_required
def page_edit(request, chapternr, page, terms):
    chapter = Chapter.objects.filter(number=chapternr).first()

    lines = Line.objects.filter(chapter__number=chapter.number, page=page).order_by('order')

    nav_box = nav(request, chapter, page, terms, True)

    if float(chapter.number) == int(float(chapter.number)):
        chapter.number = int(float(chapter.number))

    characters = Character.objects.all()
    chars = []
    for i in range(0, len(characters)):
        characters[i].line_count = Line.objects.filter(character=characters[i]).count()

        chars.append(characters[i])

    chars.sort(key=lambda x: -x.line_set.count())

    return render(request, 'ComicDatabase/page_admin.html',
                  {'chapter': chapter, 'page': page, 'terms': terms, 'lines': lines, 'nav': nav_box,
                   'characters': chars})


def search(request, terms=None):
    """List search results"""

    if request.method == 'POST':
        return HttpResponseRedirect(reverse('ComicDatabase:search', args=(request.POST.get('terms'),)))
    else:
        form = SearchForm()

    results = Line.objects.filter(text__search=terms)
    nav_box = nav(request, None, None, terms)
    return render(request, 'ComicDatabase/search.html',
                  {'results': results, 'terms': terms, 'nav': nav_box, 'form': form})


def chapter(request, chapter_number):
    """
    Show information about a chapter
    :param request: The Django request passed to the call
    :param chapter_number: The chapter number to show info about
    :return:
    """
    c = Chapter.objects.filter(number=chapter_number).first()  # type: Chapter
    if c is None:
        raise Http404('No chapter found for chapter number ' + chapter_number)

    pages = []
    for p in range(1, c.pageCount + 1):
        lines = Line.objects.filter(chapter__number=c.number, page=p)
        line_count = lines.count()

        characters = Character.objects.filter(
            line__chapter__number=chapter_number,
            line__page=p
        ).annotate(line_count=Count('line')).order_by('-line_count','name').all()

        pages.append({'number': p, 'line_count': line_count, 'characters': characters})

    return render(request, 'ComicDatabase/index_chapter.html', {
        'nav': nav(request, c), 'pages': pages, 'chapter': c
    })

ComicDatabase/templates/ComicDatabase/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BCB Database{% endblock %}</title>
    {% load static %}<link rel="stylesheet" type="text/css" href="{% static "style.css" %}"/>
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
{% block body %}
    {% block navigation %}
        {% if nav %}
            {{ nav }}
        {% else %}
            <p class="error">NAV IS MISSING!!!</p>
        {% endif %}
    {% endblock %}
    {% block contents %}
    {% endblock %}
{% endblock %}

    {% load static %}
    <script src="{% static 'jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'navdropdown.js' %}"></script>
{% block javascripts %}
{% endblock %}
</body>
</html>

ComicDatabase/templates/ComicDatabase/index_chapter.html
{% extends 'ComicDatabase/basic.html' %}
{% load static %}
{% block title %}Chapter {{ chapter.number|floatformat }}: {{ chapter.title }} | The BCB Database{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'browse.css' %}">
{% endblock %}
{% block contents %}
    <div class="singlerowcontent">
        <div id="chapterdescription">
            <div id="icon">
                <img src="https://www.bittersweetcandybowl.com/app/comics/icon/{{ chapter.number|floatformat}}.png" alt="Chapter {{ chapter.number }} icon"/>
            </div>
            <div id="description">
                <h2>Chapter {{ chapter.number|floatformat }}: {{ chapter.title }}</h2>
                <h3>{{ chapter.description }}</h3>
                <p>This chapter has {{ chapter.pageCount }} pages. As of now, {{ chapter.line_set.count }} lines have been transcribed!</p>
            </div>
        </div>

        <ul>
        {% for page in pages %}
            <li class="page">
                <h3><a href="{% url 'ComicDatabase:page' chapter.number page.number %}">Page {{ page.number }} ({{ page.line_count }} lines)</a></h3>
                <p>
                    Featuring:
                    <ul>
                    {% for character in page.characters %}
                        <li>{{ character.name }}, having {{ character.line_count }} line{{ character.line_count|pluralize }}!</li>
                    {% endfor %}
                    </ul>
                </p>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

ComicDatabase/templates/ComicDatabase/index_list.html
{% extends 'ComicDatabase/basic.html' %}
{% block title %}BCB Transcription Database{% endblock %}
{% block stylesheets %}
    {% load static %}<link rel="stylesheet" href="{% static 'browse.css' %}">
{% endblock %}
{% block contents %}
    <div class="singlerowcontent">
        <div id="about">
            <h1>The BCB Transcription Database</h1>
            <p>This website contains a (partial?) transcription database for the webcomic <a href="https://www.bittersweetcandybowl.com/">Bittersweet Candy Bowl</a>. This is a separate project; there is not relation between this website and Bittersweet Candy Bowl at all. It is run by volunteers who are fans of the comic.</p>
            <p>If you have any suggestions, please let us know! You can <a href="https://www.bittersweetcandybowl.com/chat">join the BCB IRC chat</a> or <a class="mailto" href="#">you can email me!</a> </p>
        </div>

        <ul id="chapterlist">
        {% for chapter in chapters %}
            <li class="chapter">
                <a href="{% url 'ComicDatabase:chapter' chapter.number %}">
                    <img src="https://www.bittersweetcandybowl.com/app/comics/icon/{{ chapter.number|floatformat}}.png" alt="Chapter {{ chapter.number|floatformat }} icon"/>
                    <h2>{{ chapter.title }}</h2>
                </a>
                <p>{{ chapter.description }}</p>
                <p>{{ chapter.pageCount }} pages with {{ chapter.line_set.count }} transcribed lines</p>
            </li>
        {% endfor %}
        </ul>
    </div>

{% endblock %}
{% block javascripts %}
    <script src="{% static 'mailto.js' %}"></script>
{% endblock %}

ComicDatabase/templates/ComicDatabase/login.html
{% extends 'ComicDatabase/basic.html' %}
{% block stylesheets %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "login.css" %}"/>
{% endblock %}
{% block contents %}
    <div id="loginform">
        <div class="one"><!--This is just for styling. I know, it's horrible to put display info in HTML--></div>
        <form method="post">
            {% csrf_token %}
            <h1>Log in</h1>
            <div>
                <div><label for="username">Username</label></div>
                <div><input type="text" name="username" id="username"/></div>
            </div>
            <div>
                <div>
                    <label for="password">Password</label>
                </div>
                <div>
                    <input name="password" type="password" id="password"/>
                </div>
            </div>
            <div>
                <input type="submit" value="Log in"/>
            </div>
        </form>
        <div class="two"><!--This is just for styling. I know, it's horrible to put display info in HTML--></div>
    </div>
{% endblock %}

ComicDatabase/templates/ComicDatabase/nav.html
<nav id="main">
    <ul>
        <li class="left"><a href="{% url 'ComicDatabase:index' %}">Home</a></li>
        <li class="left">
            <form method="post" action="{% url 'ComicDatabase:search' %}">
                {% csrf_token %}
                <input type="text" name="terms" placeholder="Search terms"{% if terms %} value="{{ terms }}"{% endif %}>
                <input type="submit" value="Search">
            </form>
        </li>
        {% if chapter and page %}
            <li class="left"><a href="https://www.bittersweetcandybowl.com/c{{ chapter.number }}/p{{ page }}/">Read the page on the
                BCB site</a></li>
        {% endif %}
        {% if user.is_authenticated %}
            <li class="right"><a href="{% url 'ComicDatabase:logout' %}">Log out</a></li>
            {% if page and chapter %}
                {% if not editing %}
                <li class="right"><a href="{% url 'ComicDatabase:page_edit' chapternr=chapter.number page=page %}">Edit me</a></li>
                {% else %}
                <li class="right"><a href="{% url 'ComicDatabase:page' chapternr=chapter.number page=page %}">Finished editing</a></li>
                {% endif %}
            {% endif %}
        {% else %}
            <li class="right"><a href="{% url 'ComicDatabase:login' %}">Log in</a></li>
        {% endif %}
        <li class="right">
            <select id="select_chapter" autocomplete="off">
                {% for c in all_chapters %}
                <option {% if c.number == chapter.number %}selected="selected" {% endif %}value="{{ c.number|floatformat }}">{{ c.number|floatformat }}: {{ c.title }}</option>
                {% endfor %}
            </select>
        </li>
    </ul>
</nav>

ComicDatabase/templates/ComicDatabase/page.html
{% extends 'ComicDatabase/basic.html' %}
{% block title %}
    Chapter {{ chapter.number }}, page {{ page }}
{% endblock %}

{% block stylesheets %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "browse.css" %}"/>
{% endblock %}

{% block contents %}
    <div class="search">
        {% if terms %}
            <a href="{% url 'ComicDatabase:search' terms %}">&larr;Go back to search results for
                &quot;{{ terms }}&quot;</a>
        {% endif %}
    </div>
    <div class="split">
        <div class="page">
            <a href="https://www.bittersweetcandybowl.com/c{{ chapter.number }}/p{{ page }}/">
                <img src="https://blasto.enterprises/comics/{{ chapter.number }}/{{ page }}{{ chapter.extension }}"
                     alt="Chapter {{ chapter.number }}, page {{ page }}"/>
            </a>
        </div>{% comment %}
            Commented the newline because the extra text breaks HTML
        {% endcomment %}<div class="lines">
            {% block linetable %}
            <table>
                <tr>
                    <th>Character</th>
                    <th>Line</th>
                </tr>
                {% for line in lines %}
                    <tr>
                        <td>{{ line.character.name }}</td>
                        <td>{{ line.text }}</td>
                    </tr>
                {% endfor %}
            </table>
            {% endblock %}
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        // Enable keyboard navigation
        // Use control + arrow keys to move to the next/previous page
        $(document).keypress(function (event) {
            if (!event.ctrlKey)
            {
                return;
            }
            switch (event.keyCode)
            {
                default:
                    // Any unused button
                    break;
                case 37: // left arrow
                    $('#prev_page').click();
                    break;
                case 39: // right arrow
                    $('#next_page').click();
                    break;
            }
        });
    </script>
{% endblock %}

ComicDatabase/templates/ComicDatabase/page_admin.html
{% extends 'ComicDatabase/page.html' %}
{% block title %}Editing Chapter {{ chapter.number }}, page {{ page }}{% endblock %}
{% block linetable %}
    <table>
        <tr>
            <th>Character</th>
            <th>Line</th>
            <th>Actions</th>
        </tr>
        {% for line in lines %}
            <tr>
                <td>{{ line.character.name }}</td>
                <td>{{ line.text }}</td>
                <td data-line-id="{{ line.id }}" class="actions">
                    <a href="#up" class="order" data-order-difference="-1">&uparrow;</a>
                    <a href="#down" class="order" data-order-difference="1">&DownArrow;</a>
                    <a href="#editline">&#x270E;</a>
                    <a class="delete" href="#delete">&cross;</a>
                </td>
            </tr>
        {% endfor %}
        <tr id="template">
            <td></td>
            <td></td>
            <td id="actions_template" data-line-id="" class="actions">
                <a href="#" class="order" data-order-difference="-1">&uparrow;</a>
                <a href="#" class="order" data-order-difference="1">&DownArrow;</a>
                <a href="#">&#x270E;</a>
                <a class="delete" href="#">&cross;</a>
            </td>
        </tr>
        <tr id="new_line_form">
            <td>
                <select id="new_character">
                {% for character in characters %}
                    <option value="{{ character.id }}">{{ character.name }}</option>
                {% endfor %}
                </select>
            </td>
            <td>
                <input type="text" name="line" id="new_line" placeholder="New line"/>
            </td>
            <td>
                <button id="submit_new">+</button>
            </td>
        </tr>
    </table>
{% endblock %}
{% block javascripts %}
    {{ parent }}
    {% load static %}
    <script src="{% static 'api.js' %}"></script>
    <script>
        var server = new Server({{ chapter.number }}, {{ page }});

        $("#submit_new").on('click', function () {
            var character_dropdown = document.getElementById("new_character");
            var new_line_text = document.getElementById("new_line");

            var character = {id: character_dropdown.value, name: character_dropdown.options[character_dropdown.selectedIndex].text};

            server.addLine(character, new_line_text.value, function (result) {
                if (result.Result != "OK")
                {
                    alert("Something went wrong: " + result.reason);
                    return;
                }
                var newLine = document.createElement("tr");

                var tdCharacter = document.createElement("td");
                var tdLine = document.createElement("td");
                var tdActions = document.getElementById("actions_template").cloneNode(true);
                tdActions.dataset.lineId = result.id;
                var newLineForm = document.getElementById("new_line_form");

                tdCharacter.innerHTML = result.character.name;
                tdLine.innerHTML = result.line;

                newLine.appendChild(tdCharacter);
                newLine.appendChild(tdLine);
                newLine.appendChild(tdActions);

                setupActionListeners(newLine);

                // table.childNodes = table.tbody
                newLineForm.parentNode.insertBefore(newLine, newLineForm);
            });

            // Reset input field
            character_dropdown.selectedIndex = 0;
            new_line_text.value = "";
            character_dropdown.focus();
        });

        $(".delete").on('click', deleteClick);
        /**
         * Respond to clicking a delete button
         * @param args The event arguments
         **/
        function deleteClick (args) {
            var target = args.target;
            var parent = target.parentNode;

            var lineId = parent.dataset.lineId;

            server.deleteLine(lineId, function () {
                var lineControls = $('[data-line-id=' + lineId +']')[0];
                var line = lineControls.parentNode;
                line.parentNode.removeChild(line);
            });
        }

        $("a.order").on('click', changeOrderClick);

        $("input#new_line").keyup(function (event) {
            if (event.keyCode == 13)
            {
                $("#submit_new").click();
            }
        });

        /**
         * Respond to clicking any of the order-changing buttons
         * @param event The event being fired
         */
        function changeOrderClick(event) {
            var target = event.target;
            var parent = target.parentNode;

            var lineId = parent.dataset.lineId;
            var difference = target.dataset.orderDifference;

            server.changeOrder(lineId, difference, swapAfterwards);
        }

        /**
         * A cleanup function swapping two divs after the order of some lines have been update
         * @param data The data from the server
         */
        function swapAfterwards(data)
        {
            if (data.Result != "OK")
            {
                alert('Error: ' + data.reason);
            } else {
                var lineId = data.lineId;
                var newAfterId = data.newAfterId;
                var trChanged = $('[data-line-id=' + lineId + ']')[0].parentNode;

                if (newAfterId === null)
                {
                    // Move to the beginning
                    // Already done (I think)

                } else {
                    var trAfter = $('[data-line-id=' + newAfterId + ']')[0].parentNode;
                    $(trChanged).insertAfter($(trAfter));
                    $(trAfter).insertBefore($(trChanged));
                }

                /*var trNewAfter;
                if (newAfterId !== null)
                {
                    trNewAfter = $('[data-line-id=' + newAfterId + ']')[0].parentNode;
                } else {
                    trNewAfter = null;
                }

                var container = trChanged.parentNode;

                if (trNewAfter == undefined)
                {
                    alert('Something went wrong, reload the page!');
                } else {
                    container.insertBefore(trChanged, trNewAfter);
                    if (trNewAfter != null)
                        container.insertAfter(trNewAfter, trChanged);
                }*/
            }
        }

        /**
         * Set up javascript listeners for a new line
         * @param actionBox
         */
        function setupActionListeners(actionBox)
        {
            $(actionBox).find(".delete").on('click', deleteClick);
            $(actionBox).find(".order").on('click', changeOrderClick);
        }
    </script>
{% endblock %}

ComicDatabase/templates/ComicDatabase/search.html
{% extends 'ComicDatabase/basic.html' %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static "search.css" %}"/>
{% endblock %}
{% block contents %}
    <div class="singlerowcontent">
         {% comment %}
    <form action="{% url 'ComicDatabase:search' '' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    </form>{% endcomment %}
    {% if terms %}
        <h1>Search results for &quot;{{ terms }}&quot;</h1>
    {% endif %}
    {% if results %}
        <ul class="searchresults">
            {% for result in results %}
                <li>
                    <p>&lt;{{ result.character.name }}&gt; {{ result.text }}</p>
                    <a href="{% url 'ComicDatabase:page' result.chapter.number result.page terms %}">{{ result.chapter.title }},
                        page {{ result.page }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}